# Generated by Django 4.0.1 on 2022-04-30 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        ('neighborhood', '0002_auto_20220427_1706'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pull',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date on which pull was done')),
                ('address_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='address.address')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('neighborhood_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='neighborhood.neighborhood')),
            ],
        ),
    ]
