# Generated by Django 3.2.4 on 2022-08-29 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='api_calls_remaining',
            field=models.IntegerField(default=2000),
        ),
    ]
