# Generated by Django 4.0.1 on 2022-04-30 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.TextField(help_text='Full path of the image, including S3 directory', max_length=200)),
                ('angle', models.FloatField(help_text='Angle from which image was captured', max_length=10)),
                ('year', models.TextField(help_text='Year on which image was captured', max_length=4)),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='address.address')),
            ],
        ),
    ]
