# Generated by Django 4.0.1 on 2022-04-30 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image', '0001_initial'),
        ('pull', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='pull_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pull.pull'),
        ),
    ]
