# Generated by Django 3.2.4 on 2022-06-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='places/'),
        ),
    ]
