# Generated by Django 3.2.4 on 2022-04-28 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('neighborhood', '0002_auto_20220427_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. 2384 Telegraph Ave, Berkeley, CA', max_length=200)),
                ('lat', models.CharField(help_text='keep this in mind: https://xkcd.com/2170/', max_length=100)),
                ('lng', models.CharField(help_text='keep this in mind: https://xkcd.com/2170/', max_length=100)),
                ('neighborhoods', models.ManyToManyField(to='neighborhood.Neighborhood')),
            ],
        ),
    ]
