# Generated by Django 3.2.4 on 2022-04-28 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='name',
            field=models.CharField(help_text='e.g. Midtown, Sacramento, CA', max_length=200),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='points',
            field=models.TextField(help_text='Please enter a JSON-style set of\n        (lat, lng) points that define the neighborhood in clockwise order.<br>\n        For example,<br>\n        [<br>\n        { "lat": 38.5782, "lng": -121.4852 },<br>\n        { "lat": 38.5753, "lng": -121.4746 },<br>\n        { "lat": 38.5808, "lng": -121.4722 },<br>\n        { "lat": 38.5788, "lng": -121.4649 },<br>\n        { "lat": 38.5645, "lng": -121.4711 },<br>\n        { "lat": 38.5693, "lng": -121.4891 }<br>\n        ]<br>\n        is the definition Google Maps provides for Midtown Sacramento, CA.'),
        ),
    ]
